
// This file has been generated by the GUI designer. Do not modify.
namespace Daggerfall.Editor
{
	public partial class Viewer
	{
		private global::Gtk.Notebook sectionNotebook;
		private global::Gtk.VBox gameSection;
		private global::Gtk.HBox gamePathContainer;
		private global::Gtk.Label gamePathLabel;
		private global::Gtk.FileChooserButton gamePathChooser;
		private global::Gtk.HButtonBox playButtonContainer;
		private global::Gtk.Button playButton;
		private global::Gtk.Label gameSectionLabel;
		private global::Gtk.HPaned blocksSection;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.NodeView blockList;
		private global::Gtk.Notebook notebook2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.NodeView blockChunkList;
		private global::Gtk.Label label1;
		private global::Gtk.Label blocksSectionLabel;
		private global::Gtk.GLWidget glwidget;
		private global::Gtk.Label label5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Daggerfall.Editor.Viewer
			this.Name = "Daggerfall.Editor.Viewer";
			this.Title = global::Mono.Unix.Catalog.GetString ("Daggerfall Viewer");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Daggerfall.Editor.Viewer.Gtk.Container+ContainerChild
			this.sectionNotebook = new global::Gtk.Notebook ();
			this.sectionNotebook.CanFocus = true;
			this.sectionNotebook.Name = "sectionNotebook";
			this.sectionNotebook.CurrentPage = 2;
			// Container child sectionNotebook.Gtk.Notebook+NotebookChild
			this.gameSection = new global::Gtk.VBox ();
			this.gameSection.Name = "gameSection";
			this.gameSection.Spacing = 6;
			this.gameSection.BorderWidth = ((uint)(5));
			// Container child gameSection.Gtk.Box+BoxChild
			this.gamePathContainer = new global::Gtk.HBox ();
			this.gamePathContainer.Name = "gamePathContainer";
			this.gamePathContainer.Spacing = 6;
			// Container child gamePathContainer.Gtk.Box+BoxChild
			this.gamePathLabel = new global::Gtk.Label ();
			this.gamePathLabel.Name = "gamePathLabel";
			this.gamePathLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Source path:");
			this.gamePathContainer.Add (this.gamePathLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.gamePathContainer [this.gamePathLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(7));
			// Container child gamePathContainer.Gtk.Box+BoxChild
			this.gamePathChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString("Select the folder of your Daggerfall copy."), ((global::Gtk.FileChooserAction)(2)));
			this.gamePathChooser.Name = "gamePathChooser";
			this.gamePathContainer.Add (this.gamePathChooser);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.gamePathContainer [this.gamePathChooser]));
			w2.Position = 1;
			this.gameSection.Add (this.gamePathContainer);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.gameSection [this.gamePathContainer]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child gameSection.Gtk.Box+BoxChild
			this.playButtonContainer = new global::Gtk.HButtonBox ();
			this.playButtonContainer.Name = "playButtonContainer";
			this.playButtonContainer.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child playButtonContainer.Gtk.ButtonBox+ButtonBoxChild
			this.playButton = new global::Gtk.Button ();
			this.playButton.TooltipMarkup = "Start playing Daggerfall with these settings.";
			this.playButton.CanFocus = true;
			this.playButton.Name = "playButton";
			this.playButton.UseUnderline = true;
			this.playButton.Label = global::Mono.Unix.Catalog.GetString ("Play");
			this.playButtonContainer.Add (this.playButton);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.playButtonContainer [this.playButton]));
			w4.Expand = false;
			w4.Fill = false;
			this.gameSection.Add (this.playButtonContainer);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.gameSection [this.playButtonContainer]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.sectionNotebook.Add (this.gameSection);
			// Notebook tab
			this.gameSectionLabel = new global::Gtk.Label ();
			this.gameSectionLabel.TooltipMarkup = "Manage the game and start playing.";
			this.gameSectionLabel.Name = "gameSectionLabel";
			this.gameSectionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Game");
			this.sectionNotebook.SetTabLabel (this.gameSection, this.gameSectionLabel);
			this.gameSectionLabel.ShowAll ();
			// Container child sectionNotebook.Gtk.Notebook+NotebookChild
			this.blocksSection = new global::Gtk.HPaned ();
			this.blocksSection.CanFocus = true;
			this.blocksSection.Name = "blocksSection";
			this.blocksSection.Position = 1;
			this.blocksSection.BorderWidth = ((uint)(5));
			// Container child blocksSection.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.blockList = new global::Gtk.NodeView ();
			this.blockList.CanFocus = true;
			this.blockList.Name = "blockList";
			this.blockList.Reorderable = true;
			this.GtkScrolledWindow.Add (this.blockList);
			this.blocksSection.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.blocksSection [this.GtkScrolledWindow]));
			w8.Resize = false;
			// Container child blocksSection.Gtk.Paned+PanedChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			this.notebook2.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.blockChunkList = new global::Gtk.NodeView ();
			this.blockChunkList.CanFocus = true;
			this.blockChunkList.Name = "blockChunkList";
			this.blockChunkList.Reorderable = true;
			this.GtkScrolledWindow1.Add (this.blockChunkList);
			this.notebook2.Add (this.GtkScrolledWindow1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Chunks");
			this.notebook2.SetTabLabel (this.GtkScrolledWindow1, this.label1);
			this.label1.ShowAll ();
			this.blocksSection.Add (this.notebook2);
			this.sectionNotebook.Add (this.blocksSection);
			global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.sectionNotebook [this.blocksSection]));
			w12.Position = 1;
			// Notebook tab
			this.blocksSectionLabel = new global::Gtk.Label ();
			this.blocksSectionLabel.TooltipMarkup = "Blocks are collections of parts of buildings/interior pieces, objects, people, an" +
				"d items that can be joined together in a Location under Region.";
			this.blocksSectionLabel.Name = "blocksSectionLabel";
			this.blocksSectionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Blocks");
			this.sectionNotebook.SetTabLabel (this.blocksSection, this.blocksSectionLabel);
			this.blocksSectionLabel.ShowAll ();
			// Container child sectionNotebook.Gtk.Notebook+NotebookChild
			this.glwidget = new global::Gtk.GLWidget ();
			this.glwidget.Name = "glwidget";
			this.glwidget.SingleBuffer = false;
			this.glwidget.ColorBPP = 32;
			this.glwidget.AccumulatorBPP = 0;
			this.glwidget.DepthBPP = 32;
			this.glwidget.StencilBPP = 0;
			this.glwidget.Samples = 8;
			this.glwidget.Stereo = false;
			this.glwidget.GlVersionMajor = 0;
			this.glwidget.GlVersionMinor = 0;
			this.sectionNotebook.Add (this.glwidget);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.sectionNotebook [this.glwidget]));
			w13.Position = 2;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
			this.sectionNotebook.SetTabLabel (this.glwidget, this.label5);
			this.label5.ShowAll ();
			this.Add (this.sectionNotebook);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.blocksSection.Shown += new global::System.EventHandler (this.OnBlocksPaneShown);
			this.blockList.RowActivated += new global::Gtk.RowActivatedHandler (this.OnBlockListRowActivated);
		}
	}
}
